### ISSUE TITLE
Prevent dependabot from upgrading patch versions

### ISSUE THREAD

**Issue by czerwinskilukasz1** [CatchTheTornado/askql#214]
A number of PRs from dependabot regard a patch update, meaning from A.B.X to A.B.Y, which is a minor fix, e.g. here: https://github.com/xFAANG/askql/pull/207
It would be great if it created PRs only for major and minor updates in version number (A and B).

**Comment by czerwinskilukasz1** [comment]
Following https://github.com/xFAANG/askql/issues/104, @kgajowy , could you take a look at it?

**Comment by mhagmajer** [comment]
A.B.X -> A.B.Y is actually a PATCH upgrade according to semantic versioning. Some of those may actually fix some bugs in our dependencies. Maybe we should just decrease the frequency of running dependabot? Thoughts?

**Comment by czerwinskilukasz1** [comment]
Thanks Marcin - "patch" was the word. Updated a title and description.

If there were any bugs, we could always fix them manually, but honestly, how often do you bump into a bug in libraries?  Even more, how often does a patch version fix exactly this bug at the moment you bumped into it? I'd say it's very rare.
By switching to monthly updates though, we would risk not applying security updates for several weeks.

**Comment by mhagmajer** [comment]
@czerwinskilukasz1 from my experience semantic versioning isn't really respected very often. Maybe we can have package level policies for dependabot?

**Comment by czerwinskilukasz1** [comment]
From my experience, I can't see critical security issues fixed in patch versions.
What are your examples of such projects, @mhagmajer ?

**Comment by mhagmajer** [comment]
@czerwinskilukasz1 this is just my general experience with JavaScript development. I'm okay this change. Interested to hear out what @kgajowy has to say about this too

**Comment by czerwinskilukasz1** [comment]
It turns out there is no way to prevent dependabot from upgrading patch versions, per https://github.com/dependabot/feedback/issues/256
However, we could set up automerge for patch versions. dependabot will wait for all checks to pass, so it will do the same as you or me would do as a reviewer.
@mhagmajer , if you're ok with this I will proceed.
We have 8 PRs from dependabot this week, most of them for patch versions.

**Comment by czerwinskilukasz1** [comment]
The option to disable patch updates is finally live in Dependabot! :) 
https://github.blog/changelog/2021-05-21-dependabot-version-updates-can-now-ignore-major-minor-patch-releases/

**Comment by czerwinskilukasz1** [comment]
And here is sample usage: https://github.com/dependabot/dependabot-core/issues/2219#issuecomment-843275265
