### ISSUE TITLE
Add JsonPath support 

### ISSUE THREAD

**Issue by pkarw** [CatchTheTornado/askql#575]
**Is your feature request related to a problem? If yes, please describe the problem.**

I suppose it would be great to add some resources for the [JsonPath support ](https://www.npmjs.com/package/jsonpath). This new resource, mixed with the `fetch` will make it extremely easy to query and amend the JSON responses to fit it into resulting query schema

**Describe the solution you'd like to see.**
We could add a `jsonPath` resource so the user could query the data like: 

```
let a = fetch(...)
a:jsonPath("$.store.book[*].author")
```

**Comment by pkarw** [comment]
The inspiration for this feature request was Raws.com: https://rows.com/docs/modifying-json?category=advanced

**Comment by czerwinskilukasz1** [comment]
I like the idea, because it has a concrete use case.

**Comment by pkarw** [comment]
... and it's super easy to implement in fact :-)
